modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="a_project_mine"
version="1.0.0"
displayName="Ruby Mod"
authors="Seven"
description='''
Un mod que agrega rubíes, espadas y materiales mágicos.
'''

[[dependencies.a_project_mine]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.a_project_mine]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"
